### ISSUE TITLE
Semantic Segmentation on ADE20K

### ISSUE THREAD

**Issue by Trent-tangtao** [bytedance/ibot#6]
Thank you for your outstanding work, have you tested the Semantic Segmentation on ADE20K in the code? I have encountered many problems (such as mmcv version issues and model init problems), I want to confirm that you can use this code to test normally on ADE20k？

**Comment by shallowtoil** [comment]
Hi,

Sorry for the mistakes. This is due to the compatibility issue. We run the repo with `mmsegmentation==0.12.0` and you can install by running the following command:
```
git clone -b v0.12.0 https://github.com/open-mmlab/mmsegmentation
cd mmsegmentation
pip3 install -v -e .
cd ..
```
or simply:
```
pip3 install mmsegmentation==0.12.0
```

We have updated the configuration in `INSTALL.md`.

**Comment by Trent-tangtao** [comment]
Sorry for getting back to you so late. Thanks for your kind reply!

**Comment by Trent-tangtao** [comment]
Sorry to bother you again, I ran into some problems during testing, when test in training process, there are some problems in the eval_hooks as follow: 
![image](https://user-images.githubusercontent.com/49675059/149613128-de9bf5f5-431d-4e59-8c31-e0849baac606.png)
when just test by test.py, another problem arises:
![image](https://user-images.githubusercontent.com/49675059/149613166-e9379716-0cf1-4711-a52e-3f8a650d5876.png)
I tried different versions of mmcv and mmseg but none of them worked out, hope you can provide some help

**Comment by sud0301** [comment]
While evaluating ade20k_dense_linear, I get the following error. 
`KeyError: "EncoderDecoder: 'VisionTransformer is not in the backbone registry'"`

Solution --> Starting a new terminal window after the installation resolved the issue. This issue could also appear due to GPU - cuda version mismatch.

**Comment by jensenzhoujh** [comment]
> Sorry to bother you again, I ran into some problems during testing, when test in training process, there are some problems in the eval_hooks as follow: ![image](https://user-images.githubusercontent.com/49675059/149613128-de9bf5f5-431d-4e59-8c31-e0849baac606.png) when just test by test.py, another problem arises: ![image](https://user-images.githubusercontent.com/49675059/149613166-e9379716-0cf1-4711-a52e-3f8a650d5876.png) I tried different versions of mmcv and mmseg but none of them worked out, hope you can provide some help

Hi @Trent-tangtao,

I've been recently using mmseg and encountered the first issue you mentioned `NotImplementedError: Do not know how to handle these types to promote: {'FloatTensor', 'DoubleTensor'}`. This is because the type mismatch can not be handled automatically when using apex. There are two solutions in my case. The first is not using apex when eval, i.e., commenting the apex optimizer and using the default optimizer in the config. The second is to change 
```
    total_area_intersect = torch.zeros((num_classes, ), dtype=torch.float64)
    total_area_union = torch.zeros((num_classes, ), dtype=torch.float64)
    total_area_pred_label = torch.zeros((num_classes, ), dtype=torch.float64)
    total_area_label = torch.zeros((num_classes, ), dtype=torch.float64)
```
into 
```
    total_area_intersect = torch.zeros((num_classes, ), dtype=torch.float)
    total_area_union = torch.zeros((num_classes, ), dtype=torch.float)
    total_area_pred_label = torch.zeros((num_classes, ), dtype=torch.float)
    total_area_label = torch.zeros((num_classes, ), dtype=torch.float)
```
[here](https://github.com/open-mmlab/mmsegmentation/blob/4345ee3d55a5198dc223c47e21c73b73fb44a57d/mmseg/core/evaluation/metrics.py#L97) in mmseg lib. Hope that solves your issue!
